In [76]:




# data analysis and wrangling
import pandas as pd
import numpy as np
import random as rnd

# visualization
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

# machine learning
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC, LinearSVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import Perceptron
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier







In [171]:
data = pd.read_csv('Data_Clean.csv',encoding = "ISO-8859-1")

In [72]:
data.shape

(1129, 20)

In [69]:
data.describe()

Time  Independence_Level  Extraversion_Level  Selfcontrol_level  \
count  1129.000000         1129.000000         1129.000000        1129.000000   
mean     36.627526            5.478034            5.592383           5.597254   
std      34.096597            1.703312            1.851637           1.980101   
min       0.394251            1.000000            1.000000           1.000000   
25%      11.728950            4.100000            4.600000           4.100000   
50%      24.344969            5.500000            5.400000           5.700000   
75%      51.318280            6.900000            7.000000           7.200000   
max     179.449692           10.000000           10.000000          10.000000   

       Anxiety_Level     Turnover  
count    1129.000000  1129.000000  
mean        5.665633     0.505757  
std         1.709176     0.500188  
min         1.700000     0.000000  
25%         4.800000     0.000000  
50%         5.600000     1.000000  
75%         7.100000     1.000000  
max        10.000000     1.000000

In [73]:

data.isna().sum()


Time                             0
Status                           0
Age                              0
Transport                        0
Independence_Level               0
Independence                     0
Extraversion_Level               0
Extraversion                     0
Selfcontrol_level                0
Selfcontrol                      0
Anxiety_Level                    0
Anxiety                          0
Turnover                         0
Industry_HighT_Group             0
PowerIndustry                    0
Profession_Group                 0
Risk_Group                       0
Risk_Group2                      0
RiskGroup_Profession_Industry    0
RiskGroup_Age_Anxiety            0
dtype: int64

In [71]:
print(data.columns.values)

['Time' 'Status' 'Age' 'Transport' 'Independence_Level' 'Independence'
 'Extraversion_Level' 'Extraversion' 'Selfcontrol_level' 'Selfcontrol'
 'Anxiety_Level' 'Anxiety' 'Turnover' 'Industry_HighT_Group'
 'PowerIndustry' 'Profession_Group' 'Risk_Group' 'Risk_Group2'
 'RiskGroup_Profession_Industry' 'RiskGroup_Age_Anxiety']


In [74]:
data.head()

Time  Status   Age Transport  Independence_Level Independence  \
1   7.030801    True  <=35       bus                 4.1  Independent   
2  22.965092    True  <=35       bus                 4.1  Independent   
3  15.934292    True  <=35       bus                 6.2  Independent   
4  15.934292    True  <=35       bus                 7.6  Independent   
5   8.410678    True  <=35       bus                 4.1  Independent   

   Extraversion_Level Extraversion  Selfcontrol_level      Selfcontrol  \
1                 6.2  Extraverted                5.7   NO Selfcontrol   
2                 6.2  Extraverted                5.7   NO Selfcontrol   
3                 6.2  Extraverted                2.6   NO Selfcontrol   
4                 5.4  Introverted                4.9   NO Selfcontrol   
5                 3.0  Introverted                8.0      Selfcontrol   

   Anxiety_Level      Anxiety  Turnover Industry_HighT_Group PowerIndustry  \
1            7.1      Anxious         1                Banks           BCA   
2            7.1      Anxious         1                Banks           BCA   
3            4.8   NO Anxious         1               others           MOE   
4            2.5   NO Anxious         1               others           MOE   
5            7.1      Anxious         1               others           MOE   

  Profession_Group Risk_Group  Risk_Group2 RiskGroup_Profession_Industry  \
1               HR  High Risk  Medium Risk                   Medium Risk   
2               HR  High Risk  Medium Risk                   Medium Risk   
3               HR   Low Risk  Medium Risk                   Medium Risk   
4               HR   Low Risk  Medium Risk                   Medium Risk   
5           Others  High Risk  Medium Risk                   Medium Risk   

  RiskGroup_Age_Anxiety  
1             High Risk  
2             High Risk  
3              Low Risk  
4              Low Risk  
5             High Risk

In [172]:
data= data.loc[:, ['Turnover', 'Age', 'Anxiety_Level', 'Profession_Group']]

In [86]:
data.head()

Turnover   Age  Anxiety_Level Profession_Group
1         1  <=35            7.1               HR
2         1  <=35            7.1               HR
3         1  <=35            4.8               HR
4         1  <=35            2.5               HR
5         1  <=35            7.1           Others

In [88]:
data.isna().sum()

Turnover            0
Age                 0
Anxiety_Level       0
Profession_Group    0
dtype: int64

In [173]:
X= data.loc[:, ['Anxiety_Level']]
Y= data.Turnover

In [106]:
X.shape


(1129, 1)

In [107]:
Y.shape

(1129,)

In [174]:
from sklearn.linear_model import LogisticRegression

In [175]:
logreg = LogisticRegression(solver= 'lbfgs')

In [176]:
from sklearn.model_selection import cross_val_score

In [177]:
cross_val_score(logreg, X, Y, cv=5, scoring='accuracy').mean()

0.5297187807276302

In [112]:
data.head()  #Should encode data to be able to add features in our model

Turnover   Age  Anxiety_Level Profession_Group
1         1  <=35            7.1               HR
2         1  <=35            7.1               HR
3         1  <=35            4.8               HR
4         1  <=35            2.5               HR
5         1  <=35            7.1           Others

In [178]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse= False)

In [179]:
ohe.fit_transform(data[['Age']])

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [1., 0.]])

In [180]:
ohe.categories_

[array(['<=35', '>35'], dtype=object)]

In [181]:
ohe.fit_transform(data[['Profession_Group']])

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [182]:
X = data.drop( 'Turnover', axis='columns')

In [183]:
X.head()

Age  Anxiety_Level Profession_Group
1  <=35            7.1               HR
2  <=35            7.1               HR
3  <=35            4.8               HR
4  <=35            2.5               HR
5  <=35            7.1           Others

In [184]:
from sklearn.compose import make_column_transformer #Need for features that need preprocessing, ex: encoding

In [185]:
column_trans = make_column_transformer(
    (OneHotEncoder(), ['Age','Anxiety_Level','Profession_Group']),
    remainder='passthrough')

In [186]:
column_trans.fit_transform(X)

<1129x17 sparse matrix of type '<class 'numpy.float64'>'
	with 3387 stored elements in Compressed Sparse Row format>

In [187]:
from sklearn.pipeline import make_pipeline #chaine step together

In [188]:
pipe = make_pipeline(column_trans, logreg) #take my data, transform columns and build my model logistic regression

In [189]:
cross_val_score(pipe, X, Y, cv=5, scoring='accuracy').mean() #Adding features not really improve my model

0.5349577187807276

Let's chek Age and Anxiety (Like in R)

In [194]:
#Creating new data:
X_new = X.sample(10, random_state= 1000)
X_new

Age  Anxiety_Level Profession_Group
302   <=35            3.3           Others
416   <=35            7.1               HR
155   <=35            8.7               HR
735    >35            5.6               IT
551   <=35            5.6               HR
570   <=35            6.3               HR
309   <=35            6.3               HR
510   <=35            5.6           Others
380   <=35            7.1           Others
1015  <=35            7.9           Others

In [195]:
pipe.fit(X , Y)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(),
                                                  ['Age', 'Anxiety_Level',
                                                   'Profession_Group'])])),
                ('logisticregression', LogisticRegression())])

In [196]:
#Making prediction on new data:
pipe.predict(X_new)

array([1, 0, 0, 0, 0, 0, 0, 1, 1, 1], dtype=int64)